
obj-$(CONFIG_PROTOCOL) += $(MDIR)protocol.o
obj-$(CONFIG_PROTOCOL_XMODEM) += $(MDIR)xmodem.o

cflags-$(CONFIG_PROTOCOL) += -DCONFIG_PROTOCOL
cflags-$(CONFIG_PROTOCOL_XMODEM) += -DCONFIG_PROTOCOL_XMODEM
